eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 9002
spring:
  application:
    name: zt-sms